// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy6DTCfzFAyYrBRoM8wAHB4hPVLjVDFEE',
    appId: '1:513914181670:web:2173648a3f5e6034b2aee7',
    messagingSenderId: '513914181670',
    projectId: 'mounarchtech-ac3b9',
    authDomain: 'mounarchtech-ac3b9.firebaseapp.com',
    databaseURL: 'https://mounarchtech-ac3b9-default-rtdb.firebaseio.com',
    storageBucket: 'mounarchtech-ac3b9.firebasestorage.app',
    measurementId: 'G-86LZ46SYWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzppyk8HYetSsbvPhFfJG793njHiAtwNc',
    appId: '1:513914181670:android:fe63280331ffef08b2aee7',
    messagingSenderId: '513914181670',
    projectId: 'mounarchtech-ac3b9',
    databaseURL: 'https://mounarchtech-ac3b9-default-rtdb.firebaseio.com',
    storageBucket: 'mounarchtech-ac3b9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy6DTCfzFAyYrBRoM8wAHB4hPVLjVDFEE',
    appId: '1:513914181670:web:c87559c3435339beb2aee7',
    messagingSenderId: '513914181670',
    projectId: 'mounarchtech-ac3b9',
    authDomain: 'mounarchtech-ac3b9.firebaseapp.com',
    databaseURL: 'https://mounarchtech-ac3b9-default-rtdb.firebaseio.com',
    storageBucket: 'mounarchtech-ac3b9.firebasestorage.app',
    measurementId: 'G-TGE312G26R',
  );
}
